### ISSUE TITLE
compatibility with alerta release 5.x

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#100]
Hello,
We recently updated the alerta to the newest version of 5.x & noticed that UI is failing to get any metrics.

angular.min.js:105 GET http://<our_up>:8080/api/environments?status=open&status=unknown 502 (Bad Gateway)

angular.min.js:105 GET http://<our_ip>:8080/api/alerts?status=open&status=unknown 502 (Bad Gateway)

Any pointers towards solving this would be appreciated.

**Comment by satterly** [comment]
How have you deployed Alerta? Docker? Lots of other questions but it might be easier on Gitter. https://gitter.com/alerta/chat

**Comment by sushovan23** [comment]
Sorry I debugged & found because latest version of alerta have removed the app directory. It caused imports to break in my wsgi.py
Fixed it. We can close this,

**Comment by satterly** [comment]
I've added a `Troubleshooting` section to the `README` which should hopefully help someone out in this situation in future. https://github.com/guardian/alerta#troubleshooting
