### ISSUE TITLE
Blackout UI improvements

### ISSUE THREAD

**Issue by m4ce** [alerta/angular-alerta-webui#101]
@satterly,

One thing I noticed is that I often find myself writing down the same tag when creating new blackout periods. Would it be possible for Alerta to save a history of the tags that it has seen so that then the UI can look them up? A search box where you start writing the tag and prompts you for whatever match in the database? If one types a new tag, that would also be inserted into the database so that it can be looked up later.

**Comment by satterly** [comment]
Something like this, I guess ... https://material.angularjs.org/latest/demo/autocomplete

**Comment by m4ce** [comment]
That would be awesome :)

**Comment by satterly** [comment]
I'll put it on the backlog :)
