### ISSUE TITLE
How to use OpenID Connect for authentication

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#102]
I want to use OpenID Connect for authentication. I went through the documentation & came to know we need to specify provider in config.js in the UI.

```
angular.module('config', [])
  .constant('config', {
    'endpoint'    : "/api",
    'provider'    : "google",
    'client_id'   : "INSERT-CLIENT-ID-HERE" // replace with the client id for your OAuth provider
  })
  .constant('colors', {});
```

How would above look in case of openid connect?

**Comment by satterly** [comment]
Open ID connect is a specification not an implementation. What authentication platform are you using to implement Open ID connect?

**Comment by sushovan23** [comment]
our company has a IdP (based on microsoft ADFS). They support open ID connect. So they would provide me with a client ID for my application. However I wanted to know how to configure it in alerta webui side? Do I need to write a provider code (similar to lines of google/saml)?
Also couple of other questions regarding permissions in webui - 
Is is possible to implement LDAP authentication?
Is there a way to completely remove authentication/permissions from UI. But we able to provide users with alerts view & ability to perform blackout? I am fine with providing complete access in UI without any authentication also

**Comment by satterly** [comment]
I'm no expert on ADFS but it looks like this web page could help you ... https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers
You may need to add a new "provider" to the list of supported providers. See the Keycloak example which is an OpenID connect implementation that might be very similar ... https://github.com/alerta/angular-alerta-webui/blob/master/app/js/app.js#L129
Let me know how you go or if you need any more help.

**Comment by sushovan23** [comment]
Thanks I also thought that new provider would be required. I will look into that. Also could you respond to my other two questions in previous reply. Regarding implementing ldap authentication or completely removing any permissions required in UI side?

**Comment by satterly** [comment]
LDAP is not supported by the underlying auth library that alerta web UI uses (see https://github.com/sahat/satellizer).
Yes, you can completely remove the requirement for authentication but then most features in the web UI are not available. A way around this is to use basic auth then just use a generic login like alerta/alerta.
