### ISSUE TITLE
Alert counts seem out

### ISSUE THREAD

**Issue by alistar79** [alerta/angular-alerta-webui#104]
![alerta_count_fail](https://user-images.githubusercontent.com/3536345/33015635-6b9e7d9c-cde3-11e7-9946-bb234dacb986.png)

**Comment by satterly** [comment]
Go to `/environments` and `/alerts/count` API URLs in your browser and paste the output below, please.

**Comment by alistar79** [comment]
Sorry can't seem to replicate now as mongo housekeeping has happened but I feel it could be due to expired alerts perhaps being excluded.  Was only just aware this morning when I raised this that housekeeping was needed and implemented sadly losing the state reported earlier

**Comment by satterly** [comment]
No problem. That's given me enough of a clue as to where to look. Thanks.

**Comment by alistar79** [comment]
No problem. Thanks too this is sorting out our alerts view which was mostly in email until this this month :)

**Comment by satterly** [comment]
I can't reproduce this so can't confirm that it's a problem. If it happens again grab the output from `/environments` and `/alerts/count` and we can reopen this issue. Thanks.
