### ISSUE TITLE
The web UI takes alot of time to load

### ISSUE THREAD

**Issue by ashraffouda** [alerta/angular-alerta-webui#106]
I don't know why alerta UI takes very long time to load the dash board that shows alerts
I have only 2200 alert exits

**Comment by satterly** [comment]
How are you running the Alerta API ?

If you are using the command line, like this `alertad run`, then you should use the `--with-threads` option.

**Example**
```
$ alertad run --with-threads
```
If not, let me know more about your setup. eg. nginx, apache, mod_wsgi, gunicorn, uwsgi etc.

**Comment by ashraffouda** [comment]
I'm using the same setup as in these docs 
http://alerta.readthedocs.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html#tutorial-1
I have my setup using uwsgi and nginx

**Comment by satterly** [comment]
Does it also take a long time if you use the `alerta` CLI?

**Comment by ashraffouda** [comment]
no

**Comment by satterly** [comment]
Have you tried different browsers? Do you see any errors in the browser javascript console? Are there any 400 or 500 HTTP responses in the developer console Network tab?

**Comment by ashraffouda** [comment]
I found this in console
```
angular.min.js:119 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Cc (angular.min.js:16)
    at gc (angular.min.js:93)
    at angular.min.js:94
    at q (angular.min.js:7)
    at md (angular.min.js:94)
    at f (angular.min.js:96)
    at angular.min.js:132
    at m.$eval (angular.min.js:147)
    at m.$digest (angular.min.js:144)
```

**Comment by ashraffouda** [comment]
but also something I didn't find any errors in the console, and if there is no any error it takes for ever to show alerts

**Comment by ashraffouda** [comment]
seems it was some thing related to the alert text it was too large, issue is not happening now after deleting alerts and adding alerts with small text
I *suggest* that you only view 2 or 3 lines of alert text , this would be useful if alerta is on a system that autogenerate alerts from something if the text is too long
I found some alerts with text that takes the full screen

**Comment by satterly** [comment]
That's good to know. Thanks for getting back to me on this. I'll add it to the backlog to truncate the alert "text" at some reasonable length.
