### ISSUE TITLE
lost users' list 

### ISSUE THREAD

**Issue by oyermolenko** [alerta/angular-alerta-webui#107]
it's really strange ... I have unexpectedly lost users list ... earlier I could see this list, could remove records having admin's rights ... 

Users can create accounts and log in successfully.

environment details in my previous issue

**Comment by satterly** [comment]
Can you add and delete new users? Do old users still work but you just can't see them?

**Comment by oyermolenko** [comment]
yes, old/registered users ca log in, but I don't see them in Users and can not remove

**Comment by satterly** [comment]
Are there any errors in the browser JavaScript console? What HTTP response
do you get if you go directly to the Alerta API using your browser or curl?
Can you list the users using the `alerta` cli?

**Comment by oyermolenko** [comment]
at this moment I have auth problem from alerta cli

aae@fusion> cat .alerta.conf
[DEFAULT]
timezone = Australia/Sydney
output = json
[profile production]
endpoint = http://fusion.hetz.crp:8080
key = L7h0%Z0dhdA6wK$%ygpkEyq5toxl&3%)

export ALERTA_CONF_FILE=~/.alerta.conf
export ALERTA_DEFAULT_PROFILE=production

aae@fusion> alerta uptime
Error: API key parameter 'L7h0%Z0dhdA6wK$%ygpkEyq5toxl&3%)' is invalid
aae@fusion> alerta status
Error: API key parameter 'L7h0%Z0dhdA6wK$%ygpkEyq5toxl&3%)' is invalid
aae@fusion> alerta users 
Error: API key parameter 'L7h0%Z0dhdA6wK$%ygpkEyq5toxl&3%)' is invalid
aae@fusion>

**Comment by oyermolenko** [comment]
> Can you list the users using the `alerta` cli?
I can not use key from /etc/alertad.conf to athenticate as alerta client

and there is no another key/perms to list users from cli :-(

**Comment by oyermolenko** [comment]
from my browser console
![selection_016](https://user-images.githubusercontent.com/3000740/33315107-5b14f504-d438-11e7-9d8a-e54e08b801fd.png)
![selection_015](https://user-images.githubusercontent.com/3000740/33315111-5fa38298-d438-11e7-82b4-7c3b849b82df.png)

**Comment by oyermolenko** [comment]
being playing with roles/perms

**Comment by oyermolenko** [comment]
created special API key for admin ...
use it in .alerta.conf ...
aae@fusion> export ALERTA_CONF_FILE=~/.alerta.conf
aae@fusion> export ALERTA_DEFAULT_PROFILE=production
aae@fusion> alerta users
status    updateTime    name    roles    email_verified    text    lastLogin    id    createTime    email
--------  ------------  ------  -------  ----------------  ------  -----------  ----  ------------  -------
aae@fusion>

**Comment by oyermolenko** [comment]
aae@fusion> alerta status
  AVERAGE  TYPE    NAME                       VALUE    METRIC
---------  ------  -------------------------  -------  ---------------------------
           gauge   alerts.total               521      Total alerts
100.184    timer   alerts.queries             202854   Alert queries
 28.1091   timer   alerts.counts              101064   Count alerts
  8.89276  timer   alerts.received            1591214  Received alerts
  5.875    timer   alerts.status              8        Alert status change
 27.8571   timer   alerts.tagged              7        Tagging alerts
  7        timer   alerts.untagged            1        Removing tags from alerts
  8        timer   alerts.deleted             1        Deleted alerts
           text    switch.auto-refresh-allow  ON       Alerta console auto-refresh
           text    switch.sender-api-allow    ON       API alert submission

aae@fusion> alerta uptime
11:52 up 0 days 00:40

aae@fusion> alerta version
alerta 5.0.3
alerta client 5.0.9
requests 2.18.4
aae@fusion>

**Comment by oyermolenko** [comment]
snapshoot-ed and installed alerta-server from scratch ... If you are interested in debugging please inform, I will start that VM

**Comment by oyermolenko** [comment]
a few notes: completely new installation and the problem while trying register the third user ...
obtained the error: "Error! Sign up failed. No customer lookup configured for user ..."

**Comment by satterly** [comment]
Have you got `CUSTOMER_VIEWS = True` set in your `alertad.conf` file?

**Comment by satterly** [comment]
I can see from the screen shot that you are getting 500 errors on `/users` API endpoint. If you click the gray triangle next to the start of the line it should show you the actual API response. Please paste that here. It will include an error message. Impossible to solve this without knowing what that error is.

**Comment by oyermolenko** [comment]
> Have you got CUSTOMER_VIEWS = True set in your alertad.conf file?
YES, I had .. already set to false.

**Comment by oyermolenko** [comment]
> a few notes: completely new installation and the problem while trying register the third user ...
obtained the error: "Error! Sign up failed. No customer lookup configured for user ..."

after set CUSTOMER_VIEWS = False I can add the third login ...

**Comment by oyermolenko** [comment]
> If you click the gray triangle next to the start of the line it should show you the actual API response.

NIck, thanks, correct me if I'm wrong with details API response .. pls look at attachment

![alerta_20171130](https://user-images.githubusercontent.com/3000740/33418865-8c093e9e-d5b0-11e7-9621-f9abff26c718.png)

**Comment by satterly** [comment]
I need to see the error message in the http response with the 500 status code. Click on the "Response" tab and copy and paste the output below.

![screen shot 2017-12-01 at 15 24 52](https://user-images.githubusercontent.com/615057/33489455-d95a71bc-d6ab-11e7-9ac0-3404d19e8adc.png)

**Comment by oyermolenko** [comment]
Nick, thanks for clarification 
![selection_015](https://user-images.githubusercontent.com/3000740/33540404-99ab0ba6-d8d3-11e7-89ef-62839252cd25.png)

**Comment by satterly** [comment]
Can you take a screenshot of the profile for this user? Thanks.

**Comment by oyermolenko** [comment]
![selection_015](https://user-images.githubusercontent.com/3000740/33593951-7ca418c8-d99a-11e7-823b-2807c9768b40.png)

**Comment by oyermolenko** [comment]
![selection_015](https://user-images.githubusercontent.com/3000740/33593975-a329358c-d99a-11e7-979e-028ef53378d2.png)

**Comment by satterly** [comment]
Very difficult for me to debug this without more info. If this is still an issue please provide a python exception stack trace or other information. I'll close this for now.
