### ISSUE TITLE
import API keys

### ISSUE THREAD

**Issue by oyermolenko** [alerta/angular-alerta-webui#108]
Hi,

reinstalling from scratch alerta-server discovered that it's not possible to import already created 
(previous) API keys using web intarface. It would be nice to have this feature.

Oleksandr

**Comment by satterly** [comment]
Are you using the docker container? If so, then I think this is a known issue and I'll make sure it gets fixed in the next version of the Docker container. If not, let me know. Thanks.

**Comment by oyermolenko** [comment]
no, alerta/alerta-web on the same VM based on KVM host

**Comment by satterly** [comment]
Do you host the Alerta database separately? Or on the same VM host? If you don't persist your database somewhere then you will need to restore from backups when rebuilding from scratch.
