### ISSUE TITLE
dashboard environment drawing ...

### ISSUE THREAD

**Issue by oyermolenko** [alerta/angular-alerta-webui#109]
Hi,

I guess there is a problem with drawing for CLOSED nagios events ...
Look at attachment: records for CMTP env exist but there is no tab CMTP
![selection_015](https://user-images.githubusercontent.com/3000740/33420813-ab3e5d78-d5b8-11e7-881f-c74eee63db98.png)

Oleksandr

**Comment by satterly** [comment]
Good catch. I'll take a look.

**Comment by oyermolenko** [comment]
may because of "/" in the customer name ?

**Comment by satterly** [comment]
Maybe. I hadn't noticed that. Thanks for pointing that out.

**Comment by satterly** [comment]
Sorry, but I can't reproduce this. I tried a customer with a "/" in the name and it still worked. Let me know if this is still an issue and if you can provide more info that would be useful. Thanks.

**Comment by oyermolenko** [comment]
thanks
