### ISSUE TITLE
How to add multiple tags in blackouts

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#110]
In my alerts I have set many tags which I would like to use to suppress specific alerts. How do I enter multiple tags in blackout page. When i try to enter it comes as one big tag in the blackout rule,

**Comment by satterly** [comment]
Comma-separate the tag names when you type them in like so...

![screen shot 2017-12-01 at 09 52 08](https://user-images.githubusercontent.com/615057/33477394-6f34812a-d67d-11e7-9fd4-cf07a489865e.png)

This could be clearer. I'll add it to the backlog.

**Comment by sushovan23** [comment]
Thanks for the info.
