### ISSUE TITLE
Is there a way to edit existing blackout rules?

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#111]
I would like to know if the UI supports editing existing blackout rules? I only see delete option.

**Comment by satterly** [comment]
Editing blackout rules is not currently supported. I can add this to the backlog if you want.

**Comment by sushovan23** [comment]
Thanks. please add in your backlog.

**Comment by satterly** [comment]
Done. I'll close this as it's being tracked elsewhere.
