### ISSUE TITLE
Make more options available in blackout rule

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#112]
Right now blackout rules use Environment with other options. Only exception is the possibility of using resource and event together using the Res-Event from the dropdown. It would be more powerful blackout engine if it was possible to use different combination in the rule. For example I have use case where I would like to Environment, Event & multiple tags. 
Since in version 5.x all tags from grafana are converted to alert.attributes. So it would even better if in future release it can be combination of all alert attributes.

**Comment by satterly** [comment]
My immediate reaction is that I think this would be too complex and computationally expensive to implement. However, I'll review it in more detail when I have time and get back to you. Thanks for the feedback.

**Comment by satterly** [comment]
After giving this considerable thought I have no plans to change how blackouts currently work. If you would like to provide more information on the issue feel free otherwise I will close it for now.

**Comment by satterly** [comment]
This PR https://github.com/alerta/alerta/pull/627 added support for every combination of environment, service, resource, event, group and tags. I think that addresses your issue here.
