### ISSUE TITLE
Possible bug with Blackout notify attributes setting from blackout plugin

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#114]
Following incident is observed: 
1. Blackout rule is active for Host - Server1
2. Prometheus triggered the HostUnreachable for this host. 
3. Alert was received by alerta & notfiy attribute was set to False. 
4. Based on that notify attribute the alert was suppressed. 
So far all good
Now alert is still active.
5. Blackout rule is expired. 
6. Alert is triggered again after period of 6hours. (by this time blackout rule is expired)
7. Alert is still having the attribute : notify = false
8. Due to that the plugins drop the alert & dont send out notifications. 

The issue seems to be with this piece of code in blackout plugin:
https://github.com/alerta/alerta/blob/master/alerta/plugins/blackout.py#L23-L26

the notify attribute is never set to true again. Can you have a look into it?

**Comment by satterly** [comment]
Thanks for reporting this in such a way that it made it easy to determine the root cause. This should now be fixed and will be available in the next release. 👍
