### ISSUE TITLE
I can not see acked alerts in the dashboard

### ISSUE THREAD

**Issue by ashraffouda** [alerta/angular-alerta-webui#116]
every time i ack an alert the alert disappear from the portal

**Comment by satterly** [comment]
when you ack an alert the status changes from "open" to "ack". the default filter will only show alerts that are "open". to see alerts that are "open" and "ack" status change the status filter to "active"

<img width="348" alt="screen shot 2018-01-23 at 22 57 36" src="https://user-images.githubusercontent.com/615057/35305383-098aa6e0-0091-11e8-96b7-9bf2509dd3ee.png">
