### ISSUE TITLE
[Question] : How to use openid with oauth

### ISSUE THREAD

**Issue by sushovan23** [alerta/angular-alerta-webui#117]
Hello,
This is in continuation to my earlier question: https://github.com/alerta/angular-alerta-webui/issues/102
Now we have a team which provided me with client_id and client_secret for openid connect.

How do I configure it in alerta:

config.js:
`'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'    : "/api",
    'provider'    : "",                       #what to put here
    'client_id'   : "my_client_id",
    'colors'      : {},
    'severity'    : {},
    'audio'       : {}
  });
`

I'm adding this in alerta.conf:
`OAUTH2_CLIENT_ID = 'my_id'

OAUTH2_CLIENT_SECRET = 'my_secret'
`
Please let me know how to support this.

**Comment by satterly** [comment]
You need to get that team that gave you the client_id and client_secret to give you all the information needed to implement a new provider in Alerta ...

```
// Generic OAuth 2.0
$authProvider.oauth2({
  name: null,
  url: null,
  clientId: null,
  redirectUri: null,
  authorizationEndpoint: null,
  defaultUrlParams: ['response_type', 'client_id', 'redirect_uri'],
  requiredUrlParams: null,
  optionalUrlParams: null,
  scope: null,
  scopePrefix: null,
  scopeDelimiter: null,
  state: null,
  oauthType: null,
  popupOptions: null,
  responseType: 'code',
  responseParams: {
    code: 'code',
    clientId: 'clientId',
    redirectUri: 'redirectUri'
  }
});
```

**Comment by sushovan23** [comment]
Hi,
I can get these information but could let me know where to make these changes. 
https://github.com/alerta/angular-alerta-webui/blob/master/app/js/app.js#L129

Or some other places also I would need to make change?

**Comment by sushovan23** [comment]
Hi
I got all the details listed in your last reply. I can make the changes and test it out and could contribute to this extension. 
Could you let me know where should I look to make the changes? Would change be in alerta and alerta webui side? I’ve not worked with angular yet. So would need some help in doing those changes

**Comment by sushovan23** [comment]
For my testing - I modified the https://github.com/alerta/alerta/blob/master/alerta/auth/gitlab.py
There I'm making the calls to my company provided URLs. 
I also modified the config.js accordingly with details I need. 
I had to modify app.js with redirectURL to 'http:<my_server_fqdn>:8080/#/alerts?status=open&status=unknown',

But I'm getting unusual behavior. After clicking on login it goes to the SSO page of my company & then it closes the popup but it doesnt redirect the page it just stays in /login url.

Also I put some logs in gitlab.py but have no idea how to enable or where to see those logs. 
Any inputs regarding this would help me out a lot.

**Comment by sushovan23** [comment]
I have made changes for pingfederate provider using openid. You will see the pull request sometime next week. Changes in alerta and webui projects.

**Comment by satterly** [comment]
Good work. I look forward to seeing your PR.

**Comment by medisetti** [comment]
Would you know when the pingfederate provider be merged into master?

**Comment by satterly** [comment]
Sorry I've been really busy these last few weeks. I'm currently moving countries. I'll take a look over the Easter break.

**Comment by medisetti** [comment]
Thanks for getting back, looking forward to be able to use pingfederate for sso.

**Comment by medisetti** [comment]
@sushovan23 I was trying to use you branch to test pingfedeate, I seem to be getting the code back from pingfederate, but i think it is unable to tokenezie and get info out of the code.  I suspect it is failing beyond "encoded = access_token['access_token']" in pingfederate.py, I have verified my cert and alg and  they seem to be correct. Any pointers be helpful. Thanks.

**Comment by sushovan23** [comment]
Can you tell what you are getting from your pingfederate provider? Since I worked with my provider and they ran me through the steps of first fetching 'access_token' first. Can you add some logs in the pingfederate file and check what is the response that you are getting from the provider. 

Also in order to `jwt.decode`  I installed cryptography: "2.1.4"

**Comment by sushovan23** [comment]
my provider was returning some AD (active directive) group names. I'm not making use of it. Get customer returns none or null. I'm also managing ADMIN access using the ADMIN list. 

I also had to convert the public key from x509 format to txt format to get the decoding working.
`openssl x509 -in certificate.cer -pubkey -noout > publickey.txt`


Let me know if you have any issues.
