### ISSUE TITLE
[Question] : how many users can be registered in webui?

### ISSUE THREAD

**Issue by oyermolenko** [alerta/angular-alerta-webui#118]
Hello, 

strange situation: the last registered webui my colleague don't see any notifications ... despite the previous can see... Now I have 7 users ... and at least one of us can't work here ...
Removed and re-registered by myself without success.

is there a limitation for number of webui users?

Oleksandr

**Comment by satterly** [comment]
There is no limit to the number of users. I assume there is a problem somewhere else.

**Comment by oyermolenko** [comment]
could you advice me to troubleshoot this issue?

**Comment by satterly** [comment]
This is probably best in Gitter (https://gitter.im/alerta/chat), but are you saying that you can't create new users or that you can create new users but they can't see any alerts in the console?

**Comment by oyermolenko** [comment]
added admin perms and the problem has gone
