### ISSUE TITLE
[Question] Configurable time column in alert-list

### ISSUE THREAD

**Issue by dkalashnik** [alerta/angular-alerta-webui#127]
Current view shows value for Last Receive Time. With prometheus+alertmanager that value is kinda confusing. It updates every repeat_interval (4h by default) for alerts. 
More valuable field for that stack would be Create Time. In that case we can sort alerts by real age.

Is there a way to make that configurable?

Thanks.

**Comment by satterly** [comment]
Not currently possible to configure this. It's possible to make changes to the HTML/JS to do this without too much effort. However, it's a good idea to make this configurable. I'll add it to the back log.

**Comment by satterly** [comment]
@dkalashnik Your suggestion has been implemented and will be in Alerta Release 6.1 available for download in the next few days.
