### ISSUE TITLE
Relative time

### ISSUE THREAD

**Issue by popstas** [alerta/angular-alerta-webui#135]
Would be nice to see dates in relative format, such "10 sec ago".
Should I use [urish/angular-moment](https://github.com/urish/angular-moment) or [wildlyinaccurate/angular-relative-date](https://github.com/wildlyinaccurate/angular-relative-date) to implement this?

**Comment by popstas** [comment]
Found `relativeDate` filter, added `dates.listRelative` to config.

**Comment by satterly** [comment]
Relative dates are shown in the detail page. I can add switching relative dates on and off to the backlog.
