### ISSUE TITLE
Do 5.2.1 release with changes on master

### ISSUE THREAD

**Issue by richerve** [alerta/angular-alerta-webui#140]
As discussed on https://github.com/alerta/angular-alerta-webui/issues/138, there's a major bug on version 5.2.0 that basically renders it as useless. I've tested the version on master as today and works correctly.

@satterly Can you do a bugfix release to be able to use version 5.2, thank you.

**Comment by satterly** [comment]
Done. https://github.com/alerta/angular-alerta-webui/releases/tag/v5.2.1
