### ISSUE TITLE
Customize the list of columns on the main dashboards

### ISSUE THREAD

**Issue by banzayats** [alerta/angular-alerta-webui#142]
Currently main dashboard includes the following columns:

Severity | Status | Last Receive Time | Dupl. | Environment | Service | Resource | Event | Value | Text
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Is there any way to customize them?
For example, remove **Text** and add **Tags**.

**Comment by satterly** [comment]
This is not currently possible but I'll add it to the backlog. If you can't wait you can fork the source code and make the specific changes to remove text and add tags yourself. It wouldn't be very hard. Thanks for the feedback.

**Comment by satterly** [comment]
This is now supported. See https://github.com/alerta/angular-alerta-webui/pull/165 and https://github.com/alerta/alerta/pull/707
