### ISSUE TITLE
alerta ui kiosk mode

### ISSUE THREAD

**Issue by abenaguev** [alerta/angular-alerta-webui#175]
Hi, Nick. It's me again. It's would be nice to have UI kiosk mode, when all elements except table are hided. Useful for wall-panels and so on. What your think?

**Comment by satterly** [comment]
I think it's a good idea. Is this something you are suggesting you could do? Or is this an enhancement request?

**Comment by abenaguev** [comment]
Mostly request, I think. My knowledge of frontend (especially angular) is near zero. Seems to be it's can be done with this "ng" things? I can try, but I need your advice

**Comment by satterly** [comment]
Add something like `ng-hide="isKioskMode()"` to the menu and other elements that you don't want shown in kiosk mode.

Then in the "menu" controller we'll need to add a hotkey listener that can toggle the "kiosk mode" flag if the user hits "k" or something.

Let me know if you need more help. 👍

**Comment by abenaguev** [comment]
Ok, seems to be working with help of my boss) I'll make PR later
