### ISSUE TITLE
Browser support for datetime-local input type is limited

### ISSUE THREAD

**Issue by hasso** [alerta/angular-alerta-webui#176]
Browser support for `<input type="datetime-local">` used in Alerta webui is quite limited – Firefox, Safari and IE don't support it in desktop browsers and it makes entering blackouts in these browsers quite annoying. From users perspective it would be better to use two separate inputs (date and time) or even better – [bootstrap-datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker/).

**Comment by satterly** [comment]
In the next release of the web UI it will use a date-time picker from the Vuetify framework similar to the bootstrap datetime picker.

<img width="489" alt="screenshot 2019-01-21 at 08 55 10" src="https://user-images.githubusercontent.com/615057/51459898-485fa280-1d5a-11e9-998c-379cdf5372b6.png">

I'm closing this issue as this feature won't be back-ported.
