### ISSUE TITLE
Can't get the web ui to work with alerta and github authentication

### ISSUE THREAD

**Issue by tdi** [alerta/angular-alerta-webui#18]
I have alerta 4.4.X running with the following config:
    
    DEBUG=True
     ...
    AUTH_REQUIRED = True
     ...
    OAUTH2_CLIENT_ID = 'client_id_from_github'  # Google or GitHub OAuth2 client ID and secret
    OAUTH2_CLIENT_SECRET = 'xxxxx'
    ALLOWED_GITHUB_ORGS = ['*']

In web's `config.js`:

     ...
     'provider'    : "github", // google, github, twitter or basic
     'client_id'   : "client_id_from_gihub"

When I click Login in alerta webui I get a js alert dialog (I substituted my real domain with MYDOMAIN), alertad running on port 8080, web on 8080:

      {"data":null,"status":0,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"withCredentials":true,"url":"http://MYDOMAIN:8080/auth/github","data":{"code":"e15b93d78dbfeaa87dcc","clientId":"client_id_from_github","redirectUri":"http://MYDOMAIN:8000"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":""}

**Comment by satterly** [comment]
Assuming your `CORS_ORIGINS` are set correctly in your `alertad.conf` file then this should be fixed by upgrading to alerta version 4.4.6.
