### ISSUE TITLE
Consistent display of time values

### ISSUE THREAD

**Issue by escoand** [alerta/angular-alerta-webui#181]
**Describe the solution you'd like**
Currently there is a wide diversity for displayed time values:
* Alert Create Time Diff - rounded to one unit
* Alert Timeout - seconds without unit
* Heartbeat Latency - milliseconds with unit
* Heartbeat Timeout - seconds with unit
* Heartbeat Since - minutes and seconds with unit
* maybe others
This is really inconsistent and also sometimes hard to understand. (How much are "129600 seconds" or "903 minutes 9 seconds"?)

**Describe alternatives you've considered**
Nice would be the display of the 2 highest possible units and maybe the other smaller ones as tooltip.

**Comment by satterly** [comment]
Are you aware that you can change the date formats? See https://docs.alerta.io/en/latest/configuration.html#web-ui-settings Does that help?

But I agree, there could be more consistency with things like "time since". Either way, I like the suggestion.

**Comment by escoand** [comment]
Yes, I know. But currently not possible for time diffs.

**Comment by satterly** [comment]
I'll add it to the backlog. Thanks for the feedback.
