### ISSUE TITLE
Add an icon to switch to fullscreen

### ISSUE THREAD

**Issue by Toniob** [alerta/angular-alerta-webui#185]
Hi,

It should be great to add a button to switch to fullscreen. Maybe next to the refresh button. My use case is to get alerta ui on an android tablet to monitor my platform.
Here is a documentation from mozilla : https://developer.mozilla.org/fr/docs/Web/Guide/DOM/Using_full_screen_mode

Thanks

**Comment by satterly** [comment]
If you add 'kiosk' to tha web UI URL you should get "Kiosk mode". See https://github.com/alerta/angular-alerta-webui/pull/177 Is this what you are after?

**Comment by Toniob** [comment]
Hi,
It can be a part of it. What I want is to be able to switch the browser to fullscreen mode. I'm currently running firefox on android, I want to get rid of all the window decorations, the android top bar, ... I just need the alerta web page only. Like F11 does on a desktop.
Thanks

**Comment by satterly** [comment]
This will be possible in the next major release. You can test it here https://beta.alerta.io

**Comment by Toniob** [comment]
It's working fine. Thanks. The new major release looks great. Do you have a release date ?
Is it possible to disable the screen going to sleep at the same time, please ?
http://qnimate.com/prevent-sleep-using-html5-standby-api/

**Comment by satterly** [comment]
It's only supported on Firefox OS. See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestWakeLock

Also, I don't think I'd want to be responsible for burning people's screens out. If they don't want there screen to sleep they can set that themselves in screen preferences.

No specific release date but should be some time around April of this year.
