### ISSUE TITLE
Allow a user to disable auto-updates

### ISSUE THREAD

**Issue by evaryont** [alerta/angular-alerta-webui#186]
I'm trying to do some CSS tweaks, and want to use the browser's DOM inspector to look at the HTML structure and classes. However, every time the alert list refreshes, the DOM is removed and re-added, kicking me back to the <body> element in the inspector.

Making the Auto-Update button a toggle for the timer would be allow me to temporarily stop it from refreshing the page and investigate. I don't think it should persist either.

**Comment by satterly** [comment]
This already exists. If you go to `management/switchboard` (you may need to append the `api-key` param) then you get two toggle buttons. One turns off auto-refresh.

**Example**

https://alerta-api.herokuapp.com/management/switchboard?api-key=demo-key

<img width="738" alt="screenshot 2019-01-15 at 23 34 29" src="https://user-images.githubusercontent.com/615057/51214424-28754c80-191e-11e9-9bf5-91bfb48a5c13.png">

**Comment by evaryont** [comment]
While this works, it's a global setting isn't it? What I meant to ask for is a client-side, individual and temporary option. Let an individual pause it without impacting the rest of the users.

**Comment by satterly** [comment]
You can actually do this in Chrome using the developer tools. Check the "offline" box and it won't refresh the alert list.

<img width="786" alt="screenshot 2019-01-18 at 22 16 10" src="https://user-images.githubusercontent.com/615057/51413301-c8291980-1b6e-11e9-9887-8df4ea9de445.png">
