### ISSUE TITLE
Support retreiving a custom CSS file

### ISSUE THREAD

**Issue by evaryont** [alerta/angular-alerta-webui#187]
Related to #186, I'm adding some CSS tweaks for our internal dashboard. Since we primarily have Alerta displayed on a wall, it's mostly about increasing font size and padding dramatically to make it a better "10-foot interface". Right now, I'm using this nginx configuration to intercept app.css:

```
   location =/css/app.css {
       alias /opt/alerta/custom.css;
   }
```

Which works, but it'd feel a little better if I could specify a URL in alerta's python configuration file, passed via the call to `/config` and injected by the webui. That feels more "natural", for some nebulous definition.

**Comment by satterly** [comment]
I'll add this to the backlog for the next version of the web UI.
