### ISSUE TITLE
Normal severity alerts

### ISSUE THREAD

**Issue by charlesalloum** [alerta/angular-alerta-webui#188]
**Describe the bug**
alerts are switched to severity normal but not closed directly, is there a way to specify which severity to show in the list so i can hide the normal ? or timeout for normal alerts ?

wait to receive a resolved or closed status alert

**Expected behavior**
a week ago alerts used to close automatically, now instead my list is full of "normal" alerts

**Screenshots**
![image](https://user-images.githubusercontent.com/38730842/53371858-6606c580-391f-11e9-9c78-49c643dc635c.png)

**Desktop (please complete the following information):**
 - OS: Debian Stretch
 - Browser: any

**Comment by satterly** [comment]
Your screenshot doesn't show the status of the alerts in the list so I can only assume they are all "open". 

>alerts are switched to severity normal but not closed directly, is there a way to specify which severity to show in the list so i can hide the normal ? or timeout for normal alerts ?

The web UI is not designed to filter by severity but to filter by status and sort by severity because that's how the alerts are normally managed. The normal alerts should automatically close and disappear from the main console when using the "active" filter.

You say things were working a week ago. What changed? Did you upgrade, reboot, restart after a config change? And please let me know exactly what version you are using. Thanks.

**Comment by charlesalloum** [comment]
hello, thank you for your reply, there are many people working with me on it so i don't know what was changed... can you tell me please how to set the active filter ? i have prometheus monitoring server, when alertmanager is sendin the "ok" or "resolved" status it stays open

**Comment by satterly** [comment]
Are you using Prometheus Alertmanager webhook integration? https://github.com/alerta/prometheus-config

Can you share your prometheus and alertmanager configs? Or at least the parts relevant to Alerta inegration?

**Comment by charlesalloum** [comment]
- name: 'alerta'
    webhook_configs:
    - url: 'http://tls-prometheus-tsg:8080/webhooks/prometheus'
      send_resolved: true

**Comment by charlesalloum** [comment]
![image](https://user-images.githubusercontent.com/38730842/53444215-8e53fa00-39db-11e9-96a1-712e639cbd1b.png)

**Comment by charlesalloum** [comment]
![image](https://user-images.githubusercontent.com/38730842/53444235-a0ce3380-39db-11e9-9799-61aa5e5478d7.png)

**Comment by satterly** [comment]
I'd need to see an example rules file, as well. Thanks.

I can see straight away that the status is "open" when it should be "closed". What version of Alerta are you using?

**Comment by charlesalloum** [comment]
alerta 6.7.5
alerta client 6.5.0
requests 2.21.0
click 7.0

**Comment by charlesalloum** [comment]
all my alert rule files have severity critical,warning,notice.. but no normal.. so im sure prometheus doesnt have a 'normal' severity

**Comment by satterly** [comment]
Can you copy/paste the prometheus rule below that generated the alert in question? Thanks.

**Comment by charlesalloum** [comment]
- alert: highCpuLoad1
    expr: (node_load1{subtype=~'.*postopia.*', job!~".*-(AWS|AWS-.*|ana|sad)", environment!="alpha"}  > 40)
    for: 2m
    labels:
      rulefile: postopia.yml
      severity: critical
      iris_plan: iris_plan
    annotations:
      summary: "high cpu load1 {{$value}} on  {{$labels.node}} ({{$labels.ip}} {{$labels.unifiedlocation}})"
      description: "High CPU Load1 {{$value}} on {{$labels.node}} for more than 2 minutes ({{$labels.ip}} in {{$labels.unifiedlocation}})."
(edited)

**Comment by charlesalloum** [comment]
found this too :

Feb 27 17:25:32 tls-prometheus-tsg gunicorn[99827]: INFO:flask.app:State Transition: Rule #ALL-* STATE=open     ACTION=         SET=open     SEVERITY=critical     -> normal   HISTORY=open    -> open     => SEVERITY=normal  , STATUS=open

Feb 27 17:25:32 tls-prometheus-tsg002 gunicorn[99827]: INFO:flask.app:State Transition: Rule #ALL-* STATE=open     ACTION=         SET=open     SEVERITY=normal       -> critical HISTORY=open    -> open     => SEVERITY=critical, STATUS=open

**Comment by charlesalloum** [comment]
i fixed it... i noticed that the auto close rule has a condition if state=normal.. and the default normal was 5 before i was adding more severities to alerta and i changed it in my alertad.conf to 8 which was causing the alert not to match the condition, when i put it back at 5 all normal alerts are closing

the code i found was in /usr/local/lib/python3.5/dist-packages/alerta/models/alarms/alerta.py line 115
