### ISSUE TITLE
User does not get created when using basic auth

### ISSUE THREAD

**Issue by tdi** [alerta/angular-alerta-webui#19]
When you go to `/#/signup` URI in alerta web and fill out the form, the user is not created. 

I think this is because alerta Web makes OPTIONS request, which does nothing. 

`5.172.237.230 - - [13/Jun/2015 19:54:57] "OPTIONS /auth/signup HTTP/1.1" 200 -`

**Comment by satterly** [comment]
Is there an error in the Javascript console of the browser?

**Comment by tdi** [comment]
Ok so this is yet another bug that results from not setting origins right.

**Comment by satterly** [comment]
See http://docs.alerta.io/en/latest/authentication.html#cross-origin
