### ISSUE TITLE
Frontend drop counter to 0 when switch environment tabs

### ISSUE THREAD

**Issue by RainbowHerbicides** [alerta/angular-alerta-webui#193]
In main menu when switching environment tabs, counter per environment alerts drop to 0 for all, except for current tab

Overall count:
![Screen Shot 2019-03-12 at 17 01 40](https://user-images.githubusercontent.com/441963/54210699-a7cf6880-44e8-11e9-8769-30bfbcdf7dad.png)

After switching tab:
![Screen Shot 2019-03-12 at 17 01 51](https://user-images.githubusercontent.com/441963/54210706-aaca5900-44e8-11e9-901d-bcebc075fe5e.png)

**Comment by satterly** [comment]
What version are you using?

**Comment by RainbowHerbicides** [comment]
Alerta API v6.4.0 with Postgresql as a data storage, WEB UI is v6.8.0. Sorry, was in a rush and forgot to include this info

**Comment by satterly** [comment]
I found and fixed the problem. I'll release a new version with this fix shortly.
