### ISSUE TITLE
jquery and bootstrap version upgradation in Alerta version  5.2 and 6.6

### ISSUE THREAD

**Issue by diksha-rawat** [alerta/angular-alerta-webui#196]
As part of our vulnerability hardening exercise, we are looking to  upgrade the versions for the files jquery and bootstrap which are used in alerta.  We find that these are packaged as a tar file and need your help to provide us a new tar file with the latest versions for these two.

Available version for jqeury in the tar file is 3.2.1   and required version is  3.3.1
Available version for Bootstrap  in the tar file is  3.3.7   and required version is  any version above 4.3

**Comment by satterly** [comment]
What vulnerability exercise? You don't tell me what tool you used or what the vulnerabilities were so I can't judge for myself that the results were valid. See https://github.com/jquery/jquery/issues/3927 for a good discussion about the usefulness of these types of scans in relation to JQuery.

Also, this web UI is no longer under active development and the versions of JQuery and Bootstrap will not updated any further. A new web UI has been developed and recently released. You can find it here https://github.com/alerta/alerta-webui
