### ISSUE TITLE
Alert colours

### ISSUE THREAD

**Issue by lloydpick** [alerta/angular-alerta-webui#21]
Hi,

We're about to use this UI but the colours make it very hard to read text when we have it on a display that isn't a retina monitor. Suggest changing the colours to ones that allow white text rather than black. I've attached some recommendations, ok for me to make a PR for the changes?

![screen shot 2015-08-04 at 15 40 54](https://cloud.githubusercontent.com/assets/71318/9065361/ec0372ea-3ac8-11e5-978b-acb544146981.png)

**Comment by satterly** [comment]
Thanks for the offer for the PR however I thought I'd make it configurable rather than dictating a certain colour scheme. Please test and let me know what you think. Note that I have used your color scheme in the example `config.js`

**Comment by alistar79** [comment]
Anyone got this working yet and an example config?

I have been brute forcing the config all day to try get colours for severity info,warning and a few others but no joy
