### ISSUE TITLE
Webui does not show alert

### ISSUE THREAD

**Issue by jehster** [alerta/angular-alerta-webui#23]
Hi,

I've installed alerta and webui using this doc : 
http://docs.alerta.io/en/latest/quick-start.html

Alerta works fine but Webui does not show alerts. Did I missed something in webui configuration.:
```
/var/www/alerta# alerta send -r web01 -e NodeDown -E Production -S Website -s critical -t "Web server is down." -v ERROR
8fa57d1d-e0f0-4f3d-b125-264983c7cb7b (major -> critical)
```
It looks like if webui does not requesting correctly alerta 
```
/var/www/alerta# cat config.js
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'    : "http://"+window.location.hostname+":8080",
    'provider'    : "basic", // google, github, twitter or basic
//    'client_id'   : ""
  })
  .constant('colors', {}); // use default colors
```
```
/var/www/alerta# alerta query 
d7754a6c|2015/08/19 20:25:28|normal|    0|Production|Alerta API|api.alerta.io     |Network     |up              |n/a         
   |Alerta API is up.
5bea0e23|2015/08/19 20:26:12|major|    0|Production|496780030265|InstanceId:i-0c678beb|AWS/EC2     |CPUUtilization  |ALARM       
   |CPU high
```

**Comment by satterly** [comment]
Your `config.js` is fine -- it worked for me. What do you see in the [javascript console](https://developer.chrome.com/devtools/docs/console) of your web browser? Any errors?

**Comment by jehster** [comment]
Yep, got error. It seems to be related to configuration : 
XMLHttpRequest cannot load http://10.1.3.8:8080/alerts/count?status=closed. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.1.3.8:8000' is therefore not allowed access.

Alerta is not running on my computer but on a dedicated computer.

Is it related to CORS_ORIGINS parameter ?

**Comment by satterly** [comment]
Yes, that's a `CORS_ORIGIN` thing. See docs [here](http://docs.alerta.io/en/latest/authentication.html#cross-origin).

**Comment by jehster** [comment]
Great .. it works. Thanks for helping

**Comment by satterly** [comment]
Cool. No problem.
