### ISSUE TITLE
config with AUTH_REQUIRED = False

### ISSUE THREAD

**Issue by blysik** [alerta/angular-alerta-webui#24]
I'm having issues trying to get alerta-webui working against an alerta-api that has no authorization configured.

The error console in the browser shows 404s trying to get to urls like:
https://alerta-webui.XX.XXXX.com/undefined/environments?status=open

Note the 'undefined'.  That's where it seems things are setup wrong.

I'm obviously doing something wrong here.  I've tried a config.js with just an endpoint defined, nothing else.  I've also tried with 'provider' as basic, but I think that's wrong.

**Comment by blysik** [comment]
Interestingly, it appears that my modification of config.js wasn't being picked up.

If I hard code my config into /web.js, then it starts doing the proper thing.

**Comment by satterly** [comment]
Are you trying to deploy Alerta webUI to Heroku? The Heroku [Procfile](https://github.com/alerta/angular-alerta-webui/blob/master/Procfile) is the only place where `web.js` is used.

**Comment by blysik** [comment]
Yes.  It appears that it's not picking up the config.js.

**Comment by satterly** [comment]
If you're deploying to Heroku you should make use of the [Config Vars](https://devcenter.heroku.com/articles/config-vars) to set the Alerta API endpoint for the web UI.

**Example**
<img width="400" alt="screen shot 2015-08-27 at 17 03 32" src="https://cloud.githubusercontent.com/assets/615057/9525794/c215f6d4-4cdd-11e5-824e-1aafbaea573d.png">
