### ISSUE TITLE
Bulk select not working for alt+click

### ISSUE THREAD

**Issue by poxin13** [alerta/angular-alerta-webui#32]
We are using zabbix in our environment and I greatly prefer this interface. Nice job :)

* I'd love to see an option to play a sound if there are open alerts.
* Also it would be nice when you ACK an alert if the user who did so is appended to this with a way to enter a message about it.

Bug related: I can't seem to bulk select anything. Holding alt+clicking just opens the details of an event.

**Comment by poxin13** [comment]
Odd, not seeing the commit in controllers.js for:

    $scope.getDetails = function($event,alert) {
      if ($event.metaKey || $event.altKey) {

**Comment by satterly** [comment]
Support for "alt"-clicking for windows users was added with commit 6da7ea2e4ea5fe225d0c77a114ae90b98783dbdd. And then it looks like it was lost in later commits when bulk selecting was refactored.

I've just added it back in. Download the new version of the alert console and let me know if it works -- I don't have access to a windows desktop. Thanks.

**Comment by satterly** [comment]
For reference, Mac OS X users can use the "command" key ( ⌘ ) to bulk select when clicking alerts.

**Comment by poxin13** [comment]
This has been fixed.

**Comment by satterly** [comment]
Fixed by e87b8b15c4f776ab2ed33648e70fdd97e9a537b8
