### ISSUE TITLE
Register / Login

### ISSUE THREAD

**Issue by poxin13** [alerta/angular-alerta-webui#33]
Unable to login with user created by admin in webui.

POST http://domain.com:8080/auth/signup 403 (FORBIDDEN)
controllers.js:828 Object {data: Object, status: 403, config: Object, statusText: "FORBIDDEN"}

Error! Unauthorized access. No customer lookup defined for user user@domain.com

#alertad.conf
AUTH_REQUIRED = True
ADMIN_USERS = ['admin@domain.com']
CUSTOMER_VIEWS = True
ALLOWED_EMAIL_DOMAINS = ['domain.com']
CORS_ORIGINS = [
    'http://domain.com',
]

#config.js
    'endpoint'    : "http://domain.com:8080",

**Comment by satterly** [comment]
Log in as the admin user and go the the "Configuration" -> "Customers" page. Add an entry for the user email address (or the entire email domain) and give it a customer name.

Note: Customer views are optional. If you don't want the hassle of setting up customer lookups for users the change `CUSTOMER_VIEWS` to `False`.

If you're still having trouble with this join us on [Gitter](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
Fixed by guardian/alerta#134
