### ISSUE TITLE
Add user and comment when ACKing alerts

### ISSUE THREAD

**Issue by satterly** [alerta/angular-alerta-webui#34]
it would be nice when you ACK an alert if the user who did so is appended to this with a way to enter a message about it. see #32

**Comment by poxin13** [comment]
```javascript
$scope.ackAlert = function(id, name) {
      Alert.status({id: id}, {status: 'ack', text: 'status change via ' +$auth.getPayload().name}, function(data) {
        $route.reload();
      });
    };
```

This appears to work for appending the name on alert actions. Still left is a message submission.

**Comment by satterly** [comment]
The fix adds the user name to the text when a message is acked, closed or opened (if authentication is enabled). The second part of allowing users to enter a message is left as an exercise for the reader. See a basic javascript example [here](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt).
