### ISSUE TITLE
Play sound when new alert arrives in console

### ISSUE THREAD

**Issue by satterly** [alerta/angular-alerta-webui#35]
I'd love to see an option to play a sound if there are open alerts see #32

**Comment by satterly** [comment]
It's possible (see [stackoverflow](http://stackoverflow.com/a/10107418/3626050) ). I guess it could be a configuration option to enable or disable. It has the potential for being quite annoying though. A mute button might be useful. Suggestions on how this might work in practice are welcome.

**Comment by poxin13** [comment]
I personally use this feature in Zabbix and PRTG. The audio alert if there are open / unacknowledged alerts is nice if you do not have the monitoring tab open. It only sounds about once per minute.

Soon as an alert is acknowledged, it also mutes the sound.

**Comment by poxin13** [comment]
`<audio ng-if="alerts.length > 0 && status.indexOf('open') != -1" src="sound/sound4.mp3" autoplay></audio>` to alert-list.html allows for this. Continuing down that path to allow it as a configurable option in profile.

**Comment by poxin13** [comment]
Ah, it's pretty close however this won't play the sound for any new arrivals if there are any in the alert list pre-existing.
