### ISSUE TITLE
Dynamic favicon

### ISSUE THREAD

**Issue by poxin13** [alerta/angular-alerta-webui#36]
Nice option for usability is a dynamic favicon based on the number of open alerts. Similar to the chrome extension.

**Comment by satterly** [comment]
This is possible. See Stackoverflow question [Dynamic favicon with count (like Gmail)](http://stackoverflow.com/questions/6296574/dynamic-favicon-with-count-like-gmail).

**Comment by poxin13** [comment]
Managed to get this working along with desktop notifications (chrome/firefox) and dynamic tile updates. Some other enhancements I've added are 'cursor:' for mouse over on alert list.
