### ISSUE TITLE
No datas in Dashboard

### ISSUE THREAD

**Issue by ftx** [alerta/angular-alerta-webui#46]
Hi,

Requests from WebUI arrived, and we have some datas, when i call direct api.
But no datas in the dasboard...

**Comment by satterly** [comment]
This is almost certainly a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) issue. See http://docs.alerta.io/en/latest/faq.html#why-can-t-i-see-any-alerts-in-the-web-browser

**Comment by ftx** [comment]
Yes! thanks
