### ISSUE TITLE
Old Alerta sessions are not killed if alerta docker container is stopped/killed

### ISSUE THREAD

**Issue by kavyakul** [alerta/angular-alerta-webui#51]
Hi,
I observed this problem accidently:
Step 1. Login to Alerta with a user name and leave the tab open
Step 2. Stop & remove the Alerta-web & db container
Step 3: Launch  new containers
Step 4: Go back to the Alerta page
Step 5: Still have to logout from old session, which IMHO should not be the case as existing sessions should be closed as soon as container is stopped

**Comment by satterly** [comment]
How does the Alerta web browser app know that the server has gone away permanently? Maybe it's just a transient network outage or maybe a new version of the Alerta server is being deployed?

For example, a typical scenario for redeploying web applications in the cloud is to spin up a new version while the old is running then terminate the old one when the new is ready. At no stage does the web client know (or care) that the original server that it authenticated against has gone away and been replaced. It would be a very bad user experience to force the web client to logout and make the user log back in every time we redeploy the backend server.
