### ISSUE TITLE
Alerta 4.7.5: Alerts while selecting a service

### ISSUE THREAD

**Issue by kavyakul** [alerta/angular-alerta-webui#56]
I have alerts from two environments, each having two services(common)

![alerta_1](https://cloud.githubusercontent.com/assets/15211290/16304125/af91a27a-3971-11e6-9640-c9009cd3d8b4.png)

If I select one of the service of an environment , I get alerts of that service but from both environments

![alerta_2](https://cloud.githubusercontent.com/assets/15211290/16304256/31242f74-3972-11e6-916a-935cc9388fb3.png)

I expected alerts from service of the selected environment

**Comment by satterly** [comment]
This has been fixed. Please update your Alerta console.
