### ISSUE TITLE
Problem With CORS

### ISSUE THREAD

**Issue by colomboipl** [alerta/angular-alerta-webui#62]
Cannot login or signup with config.js with basic

Its show the error "Request header field content-type is not allowed by access-control-allow-headers in preflight response.

**Comment by satterly** [comment]
What browser and version?

**Comment by colomboipl** [comment]
Chrome for centos 6.8 X64bits

**Comment by satterly** [comment]
See corydolphin/flask-cors#187

**Comment by satterly** [comment]
This is fixed by ensuring that Alerta server uses version 2.1.3 of the Flask CORS extension. However, to fix this long term it needs to be fixed in Flask CORS version 3.x so I've raised an issue with them.

**Comment by satterly** [comment]
This has been fixed upstream by Flask CORS maintainer (Flask CORS 3.0.2). Alerta server version 4.8.3 which incorporates this fix is now available for download from [Pypi](https://pypi.python.org/pypi/alerta-server/4.8.3).
