### ISSUE TITLE
WATCH

### ISSUE THREAD

**Issue by colomboipl** [alerta/angular-alerta-webui#63]
When I put an alert in watch mode the next time the alert occurs and is duplicated it erased the alert from the watch window ? 

Is this a normal behaviour ?

**Comment by satterly** [comment]
Sounds like a bug. I'll take a look.

**Comment by colomboipl** [comment]
And is alerts from nagios https://github.com/alerta/nagios-alerta

**Comment by satterly** [comment]
@colomboipl This should be fixed in Alerta server version 4.7.33. The docker container on Docker Hub has been updated to latest. And if you want help with the CORS issue let me know.

**Comment by satterly** [comment]
Ignore that last comment. I just realised you already opened #62.
