### ISSUE TITLE
missing username in log file

### ISSUE THREAD

**Issue by betorvs** [alerta/angular-alerta-webui#65]
Hi all,

I try alerta (with oauth2 + gitlab authentication config), but I don't find username when I DELETE a event. 

This log:
```
==> /tmp/alertad.log <==
127.0.0.1 - - [08/Nov/2016 10:49:51] "DELETE /alert/8100e41a-a91b-4056-8113-f414ae567d70 HTTP/1.0" 200 -

==> /var/log/nginx/access.log <==
10.1.1.67 - - [08/Nov/2016:10:49:51 -0200] "DELETE /api/alert/8100e41a-a91b-4056-8113-f414ae567d70 HTTP/1.1" 200 21 "http://alerta-web.qa.intra/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36" "-"
```

Nginx.conf logformat:
```
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```

I need to log username when someone DELETE an event. How to I configure this?

**Comment by satterly** [comment]
To get the username you would need to log the `Authorization` header and [decode the JWT bearer token](https://jwt.io/) to get the username.

![screen shot 2016-11-09 at 10 18 21](https://cloud.githubusercontent.com/assets/615057/20135102/f2562da4-a665-11e6-8dc3-f5dfb0c500b9.png)

<img width="1155" alt="screen shot 2016-11-09 at 10 21 41" src="https://cloud.githubusercontent.com/assets/615057/20135186/55b3f08e-a666-11e6-96b2-897d00012984.png">

You can get jwt decoders for any language, [including Lua](https://github.com/SkyLothar/lua-resty-jwt). So you might be able to decode the jwt and write the username to the log using an nginx Lua script.
