### ISSUE TITLE
no alert in webui

### ISSUE THREAD

**Issue by GhilesKDH** [alerta/angular-alerta-webui#75]
hello, 
i am trying to install alerta server with a web Gui (angular-alerta-webui), so i follow the documentation, every thing is ok for the server and the API, its work fine i can send alert, and it can see it in the api.. but i have some problems with the webui, the first one is that i can see any alert in the web page, CORS is setting correctly on the server, but i have this error in JS console:
![cap01](https://cloud.githubusercontent.com/assets/10399705/24667791/e422d346-1964-11e7-8c93-744196032c21.png)
any idea ?
- The second issues is that i can't create a new account based on basic provider, 
i have this error in the developer console:
![cap02](https://cloud.githubusercontent.com/assets/10399705/24668180/4ddf82ba-1966-11e7-86b6-f399a00766a2.png)

thank you for the help,

**Comment by satterly** [comment]
hi @GhilesKDH is this still a problem? i've never seen either of these errors before. i'd need to know more about your setup before i can help. how did you install alerta? is it running on docker, vagrant, ec2 or was it a standard python `pip` install?

**Comment by satterly** [comment]
Closing this issue as no update. Please reopen if you haven't resolved this issue. Thanks.
