### ISSUE TITLE
Keycloak role mapping, or ADMIN_USERS with keycloak

### ISSUE THREAD

**Issue by tkuther** [alerta/angular-alerta-webui#77]
I have updated our Alerta instance to 4.9.3 and implemented oAuth2 via keycloak LDAP user federation. The role memebership mapper is defined as explained in the documentation.

Login does work just fine. But haven't succeeded in assinging an admin role.

It seems that ADMIN_USERS is ignored (I tried using the email address or the login name)
I also tried to create an admin role in the keycloak realm (which would be a great way to define alerta admins) but that doesn't get picked up either.

Do you have some hints on how to get this working?

**Comment by satterly** [comment]
I haven't used keycloak auth myself. Looping in @m4ce . Any thoughts?

**Comment by tkuther** [comment]
Thanks!

Meanwhile I realizedthe user doesn't have any role at all - neither user nor admin. $auth.getPayload().role is undefined (added a console.log to the ProfileControlller)

**Comment by tkuther** [comment]
Bah, nevermind. For reasons I'm not aware of anymore, I changed the ADMIN_USERS variable to an array, like ADMIN_USERS=['tkuther' ,'user2']. That broke it, and all that had nothing to do with keycloak at all.

Sorry for the noise!
