### ISSUE TITLE
Question: Delete button

### ISSUE THREAD

**Issue by gabricar** [alerta/angular-alerta-webui#98]
Did I do something wrong or the delete button is disabled on the web gui?
I also try to delete it using the CLI and didn't work

[root@ansible2 ~]# alerta delete --filters id=a41293c2-d990-41bd-967d-bfa866edf28a
Counting alerts: 1, done.
Deleting alerts: ()0% (0/1)
2017-10-02 19:43:04,438 - alertaclient.api - ERROR - Missing required scope: admin:alerts

**Comment by gabricar** [comment]
I was able to enable the button but does not work
from the nginx logs:

9.50.0.6 - - [02/Oct/2017:23:30:53 -0400] "DELETE /api/alert/caf0bca5-00d8-4f32-971b-6a7c74879eb8 HTTP/1.1" 403 78 "http://172.16.0.123/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"

**Comment by satterly** [comment]
Deleting alerts is discouraged as it's a manual overhead to managing alerts that can become a difficult to maintain. It's best to automatically expire alerts that have "timed out". See http://docs.alerta.io/en/latest/gettingstarted/tutorial-2-housekeeping.html#step-2-alert-timeouts
However, if you still want to delete alerts you need to be an admin or have the "admin:alerts" permission.

**Comment by gabricar** [comment]
Thx for the reply satterly. Actually I did a couple tests and I just want to clean the alert list before put it into production. I don't want to see garbage in case a need to print a report or something like it.

Any case. thx a lot.
